name: morrolingo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.2
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_staggered_animations: ^1.1.1
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  haptic_feedback: ^0.5.1+1
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_serializable: ^6.8.0
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  vibration: ^3.1.3
  workmanager: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.4.2

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/morrolingo-icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
