name: morrolingo

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build for Sideloading
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Force iOS Deployment Target in Xcode project
        run: |
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = 18.0;/IPHONEOS_DEPLOYMENT_TARGET = 17.0;/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Clean build environment
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Install Pods
        run: pod install
        working-directory: ios

      - name: Build unsigned.app file
        run: flutter build ios --release --no-codesign

      - name: Prepare Payload directory
        run: |
          mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move app bundle to Payload
        run: |
          mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip to .ipa
        run: |
          zip -r -y FlutterIpaExport.ipa Payload/
        working-directory: build/ios/iphoneos

      - name: Upload .ipa to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          tag: v1.0.2
          overwrite: false
          body: "Morrolingo 1.0.2 🚀"

